chore: migrate to composer.final.json architecture via phpurs CLI arguments

diff --git a/bin/php/run b/bin/php/run
--- a/bin/php/run
+++ b/bin/php/run
@@ -20,12 +20,11 @@ if [ "$1" == "--x" ]; then
 fi
 
 export PATH="$PWD/run/bak/js/node_modules/.bin:$PATH"
-spago build --backend-args "--main ${ENTRY_POINT} --ffi run/bak/php/ffi" || echo "Compilation failed, but that's expected for now!"
+spago build --backend-args "--main ${ENTRY_POINT} --ffi run/bak/php/ffi --composer-in run/bak/php/composer.json --composer-out run/bak/php/composer.final.json" || echo "Compilation failed, but that's expected for now!"
 
 echo "=== Native PHP ==="
 if [ -f "output/main.php" ]; then
-    mv output/composer.json run/bak/php/composer.json
-    php bin/php/composer.phar update --no-plugins -d run/bak/php
+    COMPOSER=composer.final.json php bin/php/composer.phar update --no-plugins -d run/bak/php
     echo "<?php require __DIR__ . '/../vendor/autoload.php'; require 'main.php';" > output/run.php
     mkdir -p /tmp/phpurs_opcache
     time php -d xdebug.mode=off -d opcache.enable_cli=1 -d opcache.file_cache=/tmp/phpurs_opcache -d opcache.jit_buffer_size=128M -d opcache.jit=1255 output/run.php
